In [5]:
import geopy
dir(geopy)

['ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geokeo',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Woosmap',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [6]:
from geopy.geocoders import Nominatim
nom = Nominatim(user_agent="myGeocoder")
l = nom.geocode("175 5th Avenue NYC")
l.latitude
l.longitude #prints the latitude and longitude of the address
l

Location(Flatiron Building, 175, 5th Avenue, Flatiron District, Manhattan Community Board 5, Manhattan, New York County, New York, 10010, United States, (40.7410592, -73.9896416, 0.0))

In [2]:
import pandas as pd
df = pd.read_json("supermarkets.json")
df

,ID,Address,City,State,Country,Name,Employees
0,1,3666 21st St,San Francisco,CA 94114,USA,Madeira,8
1,2,735 Dolores St,San Francisco,CA 94119,USA,Bready Shop,15
2,3,332 Hill St,San Francisco,California 94114,USA,Super River,25
3,4,3995 23rd St,San Francisco,CA 94114,USA,Ben's Shop,10
4,5,1056 Sanchez St,San Francisco,California,USA,Sanchez,12
5,6,551 Alvarado St,San Francisco,CA 94114,USA,Richvalley,20

In [3]:
df['Address'] = df['Address'] + ',' + df['City'] + ',' + df['State'] + ',' + df['Country']
df

,ID,Address,City,State,Country,Name,Employees
0,1,"3666 21st St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Madeira,8
1,2,"735 Dolores St,San Francisco,CA 94119,USA",San Francisco,CA 94119,USA,Bready Shop,15
2,3,"332 Hill St,San Francisco,California 94114,USA",San Francisco,California 94114,USA,Super River,25
3,4,"3995 23rd St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Ben's Shop,10
4,5,"1056 Sanchez St,San Francisco,California,USA",San Francisco,California,USA,Sanchez,12
5,6,"551 Alvarado St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Richvalley,20

In [ ]:
df['Coordinates'] = df['Address'].apply(nom.geocode)
df['Lat&Long'] = df['Coordinates'].apply(lambda x: (x.latitude, x.longitude) if x else None) #creates a new column 'Lat&Long' that contains the latitude and longitude as a tuple for each address. If the geocoding fails (i.e., if x is None), it assigns None to that entry.
df
df.Coordinates[0] #prints the coordinates of the first address in the dataframe

,ID,Address,City,State,Country,Name,Employees,Coordinates,Lat&Long
0,1,"3666 21st St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Madeira,8,"(3666, 21st Street, Noe Valley, Mission, San F...","(37.7566497, -122.4294054)"
1,2,"735 Dolores St,San Francisco,CA 94119,USA",San Francisco,CA 94119,USA,Bready Shop,15,"(735, Dolores Street, Castro District, Mission...","(37.7578268, -122.4253924)"
2,3,"332 Hill St,San Francisco,California 94114,USA",San Francisco,California 94114,USA,Super River,25,"(332, Hill Street, Noe Valley, Mission, San Fr...","(37.7558363, -122.4288316)"
3,4,"3995 23rd St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Ben's Shop,10,"(3995, 23rd Street, Noe Valley, Mission, San F...","(37.7529648, -122.4317141)"
4,5,"1056 Sanchez St,San Francisco,California,USA",San Francisco,California,USA,Sanchez,12,"(1056;1058;1060;1062, Sanchez Street, Noe Vall...","(37.7521438, -122.4299768)"
5,6,"551 Alvarado St,San Francisco,CA 94114,USA",San Francisco,CA 94114,USA,Richvalley,20,"(551, Alvarado Street, Noe Valley, Mission, Sa...","(37.7535654, -122.4332486)"