In [1]:
import os
os.listdir()

['loadfile.ipynb', 'p_table.ipynb', 'p_ver.ipynb']

In [2]:
import pandas as pd

df = pd.read_json('supermarkets.json')
df = df[['ID', 'Name', 'Address', 'City', 'State', 'Country', 'Employees']]
df = df.set_index('ID')
df

,Name,Address,City,State,Country,Employees
ID,,,,,,
1,Madeira,3666 21st St,San Francisco,CA 94114,USA,8
2,Bready Shop,735 Dolores St,San Francisco,CA 94119,USA,15
3,Super River,332 Hill St,San Francisco,California 94114,USA,25
4,Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,10
5,Sanchez,1056 Sanchez St,San Francisco,California,USA,12
6,Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,20

In [7]:
df.loc[1:3, 'Name':'City'] # slicing by label
df.iloc[0:3, 0:4] # slicing by position

           Name         Address           City             State
ID
1       Madeira    3666 21st St  San Francisco          CA 94114
2   Bready Shop  735 Dolores St  San Francisco          CA 94119
3   Super River     332 Hill St  San Francisco  California 94114

In [12]:
df.drop("Address", axis=1)
df.drop([1, 2], axis=0)

,Name,Address,City,State,Country,Employees
ID,,,,,,
3,Super River,332 Hill St,San Francisco,California 94114,USA,25
4,Ben's Shop,3995 23rd St,San Francisco,CA 94114,USA,10
5,Sanchez,1056 Sanchez St,San Francisco,California,USA,12
6,Richvalley,551 Alvarado St,San Francisco,CA 94114,USA,20

In [ ]:
df["Continent"] = df.shape[0] * ["North America"]
df